### ISSUE TITLE
Apache License lacks proper copyrighting

### ISSUE THREAD

**Issue by wyndchyme** [Minecraft-3DS-Community/Minecraft-3ds-unistore#12]
The Apache License found in this repo has a copyright field at the bottom which has not been filled.

**Comment by Cracko298** [comment]
Thank you for submitting an issue, this is an invalid issue due to the fact of it being provided as a "LICENSE" file in the initial commit, if the LICENSE is out-of-date, feel free to make a pull request with the update license.

https://github.com/Minecraft-3DS-Community/Minecraft-3ds-unistore/blob/main/LICENSE

**Comment by wyndchyme** [comment]
> Thank you for submitting an issue, this is an invalid issue due to the fact of it being provided as a "LICENSE" file in the initial commit, if the LICENSE is out-of-date, feel free to make a pull request with the update license.
> 
> https://github.com/Minecraft-3DS-Community/Minecraft-3ds-unistore/blob/main/LICENSE

Not possible as such as I would not know the correct copyright information (i.e. organization? contributor?) and I think this is better left to people who are more knowledgable.

**Comment by wyndchyme** [comment]
Fixed in pull request #13
